### ISSUE TITLE
Python client fails to load documents when ID contains '+'

### ISSUE THREAD

**Issue by yanndesoutter** [ravendb/RavenDB-Python-Client#172]
Some documents of my database have an ID which contains '+' sign.
When I try to load such document by its ID, Python client only returns "None" whereas .NET version returns full document.

In attachments:
- a dump of test database, named "Python" and containing only 2 documents with ID "A+B" and "A-B"
- 2 tests projects using Python and .NET

[test-python-raven.zip](https://github.com/ravendb/ravendb-python-client/files/11026649/test-python-raven.zip)
[Dump of Python 2023-03-21 10-17.zip](https://github.com/ravendb/ravendb-python-client/files/11026659/Dump.of.Python.2023-03-21.10-17.zip)

**Comment by ayende** [comment]
Hm,
At a glance it looks like it should work:

https://github.com/ravendb/ravendb-python-client/blob/6046d8ac7cc8fbcef0145be3f47bdc2872b8f091/ravendb/documents/commands/crud.py#L272

But I can confirm that this is a problem here:
https://github.com/ravendb/ravendb-python-client/blob/6046d8ac7cc8fbcef0145be3f47bdc2872b8f091/ravendb/tools/utils.py#L341

We are passing safe values that aren't actually safe here.

**Comment by poissoncorp** [comment]
Hello @yanndesoutter 
Thank you for bringing this issue to our attention!
I've prepared a [fix](https://github.com/ravendb/ravendb-python-client/pull/173) with a passing test that confirms that the issue is not relevant anymore.

We'll publish the fix in the next release, but if it is urgent, please, let us know.
In such a case, we'll release the patch as soon as possible.
