### ISSUE TITLE
Error when importing

### ISSUE THREAD

**Issue by cekingx** [ravendb/RavenDB-Python-Client#70]
```
AttributeError: module 'ijson' has no attribute 'backend'
```
I think _ijson_ change __backend__ module into __backends__

**Comment by ayende** [comment]
Where are you running this ?

**Comment by IdanHaim** [comment]
Can you please specify your ijson package version?

**Comment by alexeyz-df** [comment]
@ayende @IdanHaim 
That happens to me as well. 
If I rememver correctly, `ijson` version was the latest one `2.5.1`
I didn't install it explicitly, that's how it came after `pip install pyravendb`

The cause seems to be that, in the fork used in pipy repo as "official" distribution v 2.5.1 https://pypi.org/project/ijson/
the `backend` is explicitly removed, pls check the last line at https://github.com/ICRAR/ijson/blob/v2.5.1/ijson/__init__.py

The way I resolved it was uninstalling ijson and installing it from https://github.com/isagalaev/ijson sources from `master`
Now I have
```
(venv3) az:~ pip freeze | grep pyravendb
pyravendb==4.0.6.1
(venv3) az:~ pip3 freeze | grep ijson
ijson==2.3
```
and it works fine. Well, at least so far.

**Comment by IdanHaim** [comment]
Thank you. ijson version bigger than 2.3 is not supported anymore.
downgrade ijson version to 2.3 will resolve the problem.

**Comment by cekingx** [comment]
Yes it work, thank you
I install ijson 2.3 using pip
