### ISSUE TITLE
How to disable topology updates

### ISSUE THREAD

**Issue by trenslow** [ravendb/RavenDB-Python-Client#86]
I'm not sure if this is the best place to file this issue, but I had a question that I can't seem to find any documentation for.

I would like to disable topology updates in my Python client, but the way I'm doing it doesn't seem to work. Digging through the client code, this was the solution I came up with:

```
store = document_store.DocumentStore(urls=db_config['urls'], database=db_config['database'])
store.conventions.disable_topology_update = True
store.initialize()
```

However, when I run my code, I see that my client is trying to connect to the database based on the topology of the server's network (separate network from where I'm developing the service that uses the client).

How can I ensure that topology updates are disabled for development?

**Comment by ayende** [comment]
`disable_topology_update` isn't doing what you think it does, I'm afraid.

It disable _future_ topologies, not the first one. 
The set of urls that you provide to the client is used to _discover_ the topology of the databases, not to set it.
This is also important since databases can move nodes.

Can you explain in a bit more detail what you are trying to do here? Note that we support multiple such networks, with the use of PublicServerUrl. 

You may also do port forwarding / hosts updates to handle that. 

You can also explicitly pass a node selector, see:
https://github.com/ravendb/ravendb-python-client/blob/v5.0/pyravendb/connection/requests_executor.py#L51

That is considered fairly advanced and isn't supported for production, though.

**Comment by ml054** [comment]
@trenslow does it solve your issue?

**Comment by trenslow** [comment]
@ml054 hi guys, sorry about the late response. Thought I had already closed this issue. 

What @ayende explained cleared up the confusion for me. Thanks for that! Will open a separate issue if I’m confused again.
